"""
Documentation Generator Module

This module provides functionality to generate Markdown documentation
from parsed Python code structure using Jinja2 templates.
"""

import os
from typing import Dict, List, Any, Optional
from jinja2 import Environment, FileSystemLoader, Template, TemplateNotFound


def generate_markdown(
    structure: Dict[str, List[Dict[str, Any]]],
    template_dir: str,
    template_name: str,
    module_name: str,
    summary: Optional[str] = None
) -> str:
    """
    Generate Markdown documentation from a parsed structure using a Jinja2 template.
    
    Args:
        structure: Parsed structure dictionary from parser.parse_python_file()
        template_dir: Directory containing Jinja2 templates
        template_name: Name of the template file to use
        module_name: Name of the module being documented
        summary: Optional summary text (e.g., from git analysis)
        
    Returns:
        str: Generated Markdown content
        
    Raises:
        TemplateNotFound: If the specified template does not exist
        Exception: If template rendering fails
        
    Example:
        >>> structure = parse_python_file('my_module.py')
        >>> markdown = generate_markdown(
        ...     structure,
        ...     'templates',
        ...     'module.md.j2',
        ...     'my_module.py',
        ...     'Recent updates to error handling'
        ... )
        >>> print(markdown)
    """
    try:
        # Create Jinja2 environment
        env = Environment(
            loader=FileSystemLoader(template_dir),
            trim_blocks=True,
            lstrip_blocks=True,
            keep_trailing_newline=True
        )
        
        # Load the template
        template = env.get_template(template_name)
        
        # Render the template with data
        output = template.render(
            module_name=module_name,
            structure=structure,
            summary=summary,
            module_docstring=structure.get('module_docstring')
        )
        
        return output
        
    except TemplateNotFound:
        raise TemplateNotFound(f"Template not found: {template_name} in {template_dir}")
    except Exception as e:
        raise Exception(f"Error rendering template: {str(e)}")


def generate_markdown_from_string(
    structure: Dict[str, List[Dict[str, Any]]],
    template_string: str,
    module_name: str,
    summary: Optional[str] = None
) -> str:
    """
    Generate Markdown documentation from a template string.
    
    Useful for testing or when templates are stored in memory/database.
    
    Args:
        structure: Parsed structure dictionary from parser.parse_python_file()
        template_string: Jinja2 template as a string
        module_name: Name of the module being documented
        summary: Optional summary text
        
    Returns:
        str: Generated Markdown content
        
    Raises:
        Exception: If template rendering fails
    """
    try:
        template = Template(template_string)
        output = template.render(
            module_name=module_name,
            structure=structure,
            summary=summary,
            module_docstring=structure.get('module_docstring')
        )
        return output
    except Exception as e:
        raise Exception(f"Error rendering template string: {str(e)}")


def save_markdown(content: str, output_path: str) -> None:
    """
    Save generated Markdown content to a file.
    
    Creates parent directories if they don't exist.
    
    Args:
        content: Markdown content to save
        output_path: Path where the file should be saved
        
    Raises:
        Exception: If file writing fails
    """
    try:
        # Create parent directories if they don't exist
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
    except Exception as e:
        raise Exception(f"Error saving markdown to {output_path}: {str(e)}")


def generate_index_page(
    modules: List[Dict[str, str]],
    template_dir: str,
    project_name: str = "Project Documentation"
) -> str:
    """
    Generate an index page listing all documented modules.
    
    Args:
        modules: List of module dictionaries with 'name' and 'path' keys
        template_dir: Directory containing templates
        project_name: Name of the project
        
    Returns:
        str: Generated index page Markdown
    """
    index_template = """# {{ project_name }}

## Modules

{% for module in modules %}
- [{{ module.name }}]({{ module.path }})
{% endfor %}

---

*Documentation generated by CodeScribe*
"""
    
    template = Template(index_template)
    return template.render(project_name=project_name, modules=modules)


if __name__ == "__main__":
    # Example usage
    import sys
    from .parser import parse_python_file
    
    if len(sys.argv) > 1:
        file_path = sys.argv[1]
        try:
            # Parse the file
            structure = parse_python_file(file_path)
            
            # Generate markdown
            module_name = os.path.basename(file_path)
            markdown = generate_markdown(
                structure,
                'templates',
                'module.md.j2',
                module_name
            )
            
            # Print to stdout
            print(markdown)
            
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print("Usage: python generator.py <python_file>")
        sys.exit(1)
